resources:
  - ../../base

patches:
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: portal-root

  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: portal-root